# Generated by Django 3.2.7 on 2021-11-30 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'component',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'componenttype',
            },
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_component', models.ForeignKey(db_column='id_component', on_delete=django.db.models.deletion.CASCADE, to='api.component')),
            ],
            options={
                'db_table': 'composition',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('salary', models.IntegerField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('blueprint', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'machine',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'machinetype',
            },
        ),
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ordertype',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(db_column='type', max_length=255)),
            ],
            options={
                'db_table': 'shoptype',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tool',
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_roles', models.ForeignKey(db_column='id_roles', on_delete=django.db.models.deletion.CASCADE, to='api.roles')),
            ],
            options={
                'db_table': 'userroles',
            },
        ),
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiredate', models.DateField()),
            ],
            options={
                'db_table': 'warranty',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=255)),
                ('id_customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('roles', models.ManyToManyField(through='api.UserRoles', to='api.Roles')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='userroles',
            name='id_user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.CASCADE, to='api.users'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('allowed', models.BooleanField()),
                ('status', models.CharField(max_length=255)),
                ('date_manufactured', models.DateField(db_column='datemanufactured')),
                ('id_machine', models.ForeignKey(db_column='id_machine', on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
            options={
                'db_table': 'unit',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('id_ShopType', models.ForeignKey(db_column='id_shoptype', on_delete=django.db.models.deletion.CASCADE, to='api.shoptype')),
            ],
            options={
                'db_table': 'shop',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('comment', models.CharField(max_length=255)),
                ('id_Customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.CreateModel(
            name='RequiredTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_machine', models.ForeignKey(db_column='id_machine', on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
                ('id_tool', models.ForeignKey(db_column='id_tool', on_delete=django.db.models.deletion.CASCADE, to='api.tool')),
            ],
            options={
                'db_table': 'requiredtools',
            },
        ),
        migrations.CreateModel(
            name='RepairAppl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('period', models.DateField()),
                ('id_Customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('id_Machine', models.ForeignKey(db_column='id_machine', on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
            options={
                'db_table': 'repairappl',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('id_Component', models.ForeignKey(db_column='id_component', on_delete=django.db.models.deletion.CASCADE, to='api.component')),
                ('id_Provider', models.ForeignKey(db_column='id_provider', on_delete=django.db.models.deletion.CASCADE, to='api.provider')),
            ],
            options={
                'db_table': 'producttype',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=255)),
                ('id_Customer', models.ForeignKey(db_column='id_customer', on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('id_Employee', models.ForeignKey(db_column='id_employee', on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('id_OrderType', models.ForeignKey(db_column='id_ordertype', on_delete=django.db.models.deletion.CASCADE, to='api.ordertype')),
                ('id_Warranty', models.ForeignKey(db_column='id_warranty', on_delete=django.db.models.deletion.CASCADE, to='api.warranty')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('blueprint', models.CharField(max_length=255)),
                ('components', models.ManyToManyField(through='api.Composition', to='api.Component')),
                ('id_machine', models.ForeignKey(db_column='id_machine', on_delete=django.db.models.deletion.CASCADE, to='api.machine')),
            ],
            options={
                'db_table': 'node',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='id_machinetype',
            field=models.ForeignKey(db_column='id_machinetype', on_delete=django.db.models.deletion.CASCADE, to='api.machinetype'),
        ),
        migrations.AddField(
            model_name='machine',
            name='tools',
            field=models.ManyToManyField(through='api.RequiredTools', to='api.Tool'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_Shop',
            field=models.ForeignKey(db_column='id_shop', on_delete=django.db.models.deletion.CASCADE, to='api.shop'),
        ),
        migrations.AddField(
            model_name='composition',
            name='id_node',
            field=models.ForeignKey(db_column='id_node', on_delete=django.db.models.deletion.CASCADE, to='api.node'),
        ),
        migrations.AddField(
            model_name='component',
            name='id_componenttype',
            field=models.ForeignKey(db_column='id_componenttype', on_delete=django.db.models.deletion.CASCADE, to='api.componenttype'),
        ),
    ]
